### ISSUE TITLE
area not displayed when editing

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#1859]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the bug still present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report - the change will be part of the next Markor update.

### Description

Recently, it sometimes happens that when editing, an area above the action list does not display the content. When this happens is hard to say. If you then hide the keyboard and show it again, the whole area above the action list is used for display again.

![Screenshot_2022-09-27-01-36-14-915_net gsantner markor](https://user-images.githubusercontent.com/9020187/192401578-73bcf02b-b6cf-42f6-bbab-06e83db2f38c.jpg)

### Steps to reproduce

hard to reproduce, but it happens often enough and in several versions. First I have seen this a few weeks ago 

### Information

Android version: 12
Device: Poco M4 pro
App Version: 2.10.4 (140)

### Source

F-Droid

### Format / File type

Plaintext

### Additional info / Log

```shell
I did not check Morder, but it is not possible to post the issue without this checkbox.
```

**Comment by aisbergde** [comment]
the visible area can be scrolled. It looks like the editable window is just to small.

**Comment by gsantner** [comment]
I cannot reproduce. Maybe keyboard specific.

**Comment by harshad1** [comment]
This happens to me from time to time too, and has been happening for a long time. Not sure why or how and I haven't yet found a way to consistently reproduce it.

**Comment by gsantner** [comment]
I'm closing this one as I can't reproduce it either, or it's really hard to reproduce. If somebody gets this often, can reproduce it easily, Markor is happy about merge requests to fix the issue. It can't be fixed by guessing.

**Comment by harshad1** [comment]
Try the following steps to reproduce:

1. Create a new file
2. Insert a long snippet (more than 1 screen worth)
3. The issue appears

Just typing or pasting content does not trigger the issue.

Sep. 28, 2022 11:40:53 Gregor Santner ***@***.***>:

**Comment by gsantner** [comment]
So do you t

**Comment by gsantner** [comment]
In that exact scenario I found it to happen as well @harshad1 . Though just like you say, never generally when editing or pasting.

**Comment by aisbergde** [comment]
In the past I did not use snippets, but it also happened.
It could be related to new created files, not sure.
I think it is also related to switching between Markor and other apps.
I will have a look on it, and if it happens again and I will find some "rules", I can add information here.

**Comment by harshad1** [comment]
Seems to happen only with new files. Closing an opening the file again causes it to go away.

The issue is relate to the padding size. The padding regions hide the text (the issue is seen at the top too, but the top padding is 16dp, not 120dp like it is at the bottom)

**Comment by gsantner** [comment]
Can this still be reproduced on master? I recall some recent layout changes so might be not happen anymore

**Comment by harshad1** [comment]
Yes, 100% of the time if you create a new empty file and type / paste content in.

Opening a file with existing content somehow eliminates the issue. I tried debugging this but I got nowhere looking at the layout inspector.

Nov. 5, 2022 05:36:49 Gregor Santner ***@***.***>:

**Comment by gsantner** [comment]
hm, if 100% empty is the problem: Maybe setting xml `<EditText android:text="space" android:....>` one space in xml there so edittext inits fonts and stuff properly? Anyway is going to be overwritten on file load

**Comment by gsantner** [comment]
Please try this build <https://github.com/gsantner/markor/actions/runs/3445179604>. With this minor change I couldn't reproduce it anymore at last.

**Comment by aisbergde** [comment]
I don't know, how to build different named apps from different branches or different forks.

**Comment by gsantner** [comment]
Temporary uninstall mordor, install CI build, test it, and then continue as usual

**Comment by aisbergde** [comment]
It is not very useful for me to test features and bug fixes if the AsciiDoc support I implemented is not available. Then I better wait until I can combine everything in one build.

**Comment by gsantner** [comment]
Look, this is meant to be installed, tested "does it work like it should", uninstall. A thing for 5-10 minutes :-D. If you don't want to do that, fine. Sometimes there are 5 PRs open at same time, and I neither mix&match - after all the changes need to be looked standalone - just as they would go into the app in first stage.

**Comment by gsantner** [comment]
@harshad1 can you reproduce the bug still with the mentioned change/build above? It worked here at last

**Comment by gsantner** [comment]
?

**Comment by gsantner** [comment]
@harshad1 can you reproduce the bug still with the mentioned change/build above? It worked here at last

**Comment by harshad1** [comment]
More interesting data:

- If you are experiencing this issue, changing font size or wrap state will fix it
- If you have a file open which does not exhibit this issue and delete enough of a file so that all the text fits on one screen with no scrollbar present, the issue will reappear
- When this issue is present, no scrollbar appears and kinetic (fling) scroll does not work.

I am convinced that this issue arises due to the interaction of the scrollview and the edit text

**Comment by harshad1** [comment]
Setting the layout_height to wrap_content and minHeight to 1dp seems to solve this issue. Will add this to the PR.

**Comment by harshad1** [comment]
This should be solved now. @aisbergde please confirm with latest dev build

**Comment by aisbergde** [comment]
it is hard to confirm or not confirm, because sometimes it happens, most time not. And it looks like it happens mostly on new created files. In the last time I used the f-droid version 2.10.7 (143) and it didn't happen. I could only report, if it happens again. For now it's fine.
