### ISSUE TITLE
Codeblocks syntax highlighting

### ISSUE THREAD

**Issue by AZeed18** [gsantner/markor#2372]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Codeblocks are no longer rendered as codeblocks in editor mode

![](https://github.com/user-attachments/assets/141def18-2aef-45dd-bd9a-c5d2387d2efd)

### Steps to reproduce

1. 
2. 
3. 

### Information

Android version: 13
Device: Samsung Galaxy A71
App Version: 

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
Check issues.

**Comment by gsantner** [comment]
Search issues..

**Comment by AZeed18** [comment]
> Search issues.. this was changed and asked in the last 24 hours..

Can't find I but anyways thanks.

**Comment by gsantner** [comment]
It was you yourself that asked https://github.com/gsantner/markor/issues/2364#issuecomment-2253731594

**Comment by AZeed18** [comment]
Yes, just thought I commented in an irrelevant issue

**Comment by gsantner** [comment]
Ah ok, yes thats right but was fixed shortly after

**Comment by AZeed18** [comment]
@gsantner I wonder why the issue still exists in latest build from master... and also header-like text in codeblocks still shows in table of contents...

**Comment by harshad1** [comment]
Could you post a screenshot of how these used to look and which version they last looked as expected?

**Comment by AZeed18** [comment]
I tried some old releases and ended at v2.8.1 and they looked the same as here, I got confused since I used PC for most of the editing

So, the issue is not specific to any release

**Note:** the issue is related to editor mode only

**Comment by gsantner** [comment]
Your question is about syntax highlighting in editor then. Not (Markdown) rendering.

Yes the codeblock are only limited syntax highlighted, as font, colors are performance tanking.

**Comment by gsantner** [comment]
Your question is about syntax highlighting in editor then. Not (Markdown) rendering.

Yes the codeblocks are only limited syntax highlighted or special treated compared to the rest. Also font, colors are performance tanking when done whole block wise. 

This topic was asked and replied so many times in the last years.

**Comment by AZeed18** [comment]
Yes, you are right...

Maybe disable special formatting completely for anything inside code blocks (to appear just white with default font)

**Comment by AZeed18** [comment]
Maybe like this, just to appear different

![](https://github.com/user-attachments/assets/8b8a8f95-c9b3-4f52-b604-01fd36460047)

**Comment by gsantner** [comment]
It is not that easy going. Like said, coloring whole block is 
performance criticial. Whats even more performance critial is when we 
need to add a rule to EVERYTHING to not trigger in code blocks. So every 
tiny bit of syntax highlighting needs to be suddenly look back and forth 
if it's in a code block. Looking back and forward across the whole file 
with regex is very bad.

**Comment by AZeed18** [comment]
I thought it could be easy to identify code blocks in a file with a single rule and skip them in any formatting, but anyways this feature may not be worth much work

**Comment by gsantner** [comment]
As I said, when you want to teach rules to skip syntax highlighting in code block you need to scan the file. And that for each of the like 20 regex need to be adapted (and made much much worse in performance).
